### ISSUE TITLE
原书的疑问

### ISSUE THREAD

**Issue by rootkiter** [iotwuxi/iot_security#1]
原书16页，设置 mbedtls 环境变量时，给了两行命令
```
$ echo "export MBEDTLS_BASE=<mbedtls 源代码仓库安装路径>" >> $HOME/.bashrc
$ source $HOME/.bashrc
```

请问，第一行命令中"源代码仓库安装路径" 是哪个路径，读了半天也没读懂。源码路径？仓库路径？安装路径？

**Comment by xianrenqiu** [comment]
> 原书16页，设置 mbedtls 环境变量时，给了两行命令
> 
> ```
> $ echo "export MBEDTLS_BASE=<mbedtls 源代码仓库安装路径>" >> $HOME/.bashrc
> $ source $HOME/.bashrc
> ```
> 
> 请问，第一行命令中"源代码仓库安装路径" 是哪个路径，读了半天也没读懂。源码路径？仓库路径？安装路径？

不好意思，可能没有描述清楚，MBEDTLS_BASE 环境变量为 mbedtls 源码的路径

**Comment by xukai871105** [comment]
举个例子，把mbedtls的源代码安装到 /Users/xukai/repo_github/mbedtls ，那么此时 MBEDTLS_BASE = /Users/xukai/repo_github/mbedtls，在.bashrc文件中增加一行 export MBEDTLS_BASE=/Users/xukai/repo_github/mbedtls

**Comment by rootkiter** [comment]
感谢两位大佬～
