### ISSUE TITLE
本人基础薄弱问个基础的问题,dh中的问题

### ISSUE THREAD

**Issue by bht2311064** [iotwuxi/iot_security#2]
mbedtls_mpi_read_string(&dhm_srv.P, 16, T_P);
mbedtls_mpi_read_string(&dhm_srv.G, 10, GENERATOR);
这函数参数中的16,10,还有t_p还有generator,分别什么意思,如果在实际工作中必须要用到这个函数吗

**Comment by xianrenqiu** [comment]
mbedtls_mpi_read_string 是将 16进制字符串或 10进制字符串读取到 mbedtls_mpi 结构中，16 和 10 表示字符串的格式，generator 为有限循环群的生成元；

举个栗子，RFC 7919 中的生成元和素数P 定义如下：
![image](https://user-images.githubusercontent.com/9956984/71789458-242dcc00-3066-11ea-812b-f72827726138.png)

**Comment by bht2311064** [comment]
thank you
