### ISSUE TITLE
dump_buf函数实现未使用参数buf

### ISSUE THREAD

**Issue by zhaoshuangcai** [iotwuxi/iot_security#7]
【问题页面】https://github.com/iotwuxi/iot_security/blob/master/02_start/linux/base64/base64.c

【问题描述】iot_security/02_start/linux/base64/base64.c 中 dump_buf 函数实现未使用参数buf，而是使用了代码中的全局变量msg。

文件iot_security/02_start/linux/base64/base64.c 中dump_buf函数实现如下：
```
void dump_buf(char *info, uint8_t *buf, uint32_t len)
{
    mbedtls_printf("%s", info);
    for(uint32_t i = 0; i < len; i++) {
        mbedtls_printf("%02x ", msg[i]);
    }
    mbedtls_printf("\n");
}
```

【建议原因】代码base64.c中dump_buf只被用于打印了msg，运行结果正常；若使用dump_buf打印其它变量，则逻辑会出错。

建议修改为：
```
void dump_buf(char *info, uint8_t *buf, uint32_t len)
{
    mbedtls_printf("%s", info);
    for(uint32_t i = 0; i < len; i++) {
        mbedtls_printf("%02x ", buf[i]);
    }
    mbedtls_printf("\n");
}
```

**Comment by xianrenqiu** [comment]
@zhaoshuangcai    感谢反馈， 问题已修正；
